# Redirect next/image requests to Netlify Image CDN
[[redirects]]
from = "/_next/image/*"
query = { q = ":quality", url = ":url", w = ":width" }
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200
force = true


[[redirects]]
from = "/*"
to = "/index.html"
status = 200
